feat: readme updated

diff --git a/dmoji b/dmoji
--- a/dmoji
+++ b/dmoji
@@ -1,4 +1,17 @@
 #!/usr/bin/env bash
+# -----------------------------------
+#| bgll.fullstackfullstock.com       |
+#| github.com/babidiii               |
+# -----------------------------------
+
+
+#[[-------------------------------------------------------------------- Settings
+set -o errexit   # abort on nonzero exitstatus
+set -o nounset   # abort on unbound variable
+set -o pipefail  # don't hide errors within pipes
+# set -o xtrace  # for debug : could use bash -x prog instead 
+#]]
+
 
 emoji=$(cat emoji-list.txt | dmenu -i -l 20 -p "Emoji :" | cut -d '(' -f 2 | cut -d ')' -f1 | xargs echo -n )
 
@@ -6,6 +19,6 @@ if [[ $emoji == *".."* ]]; then
   echo "${emoji}" | tr -s '.' | sed 's/\./\n/g' | dmenu -i -l 5 -p "Choose:" | xargs echo -n | xclip -sel clip
 
 else 
-   echo "${emoji}" | xclip -sel clip
+   echo -n "${emoji}" | xclip -sel clip
 fi
 
